apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: mujahid28/wordpress:latest
        ports:
        - containerPort: 80
        env: 
        - name: WORDPRESS_DB_HOST
          value: db
        - name: WORDPRESS_DB_USER
          value: mujahid
        - name: WORDPRESS_DB_PASSWORD
          value: admin123
        - name: WORDPRESS_DB_NAME
          value: wordpress
    ports:
      - "80:80"
    restart: always
   
